### ISSUE TITLE
Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (64)

### ISSUE THREAD

**Issue by tan-tan-kanarek** [kaltura/developer-platform#73]
+ lucybot build --prerender --destination generated/ott --basePath /doc/
Building documentation in /home/dev/jenkins/workspace/Generate-Docs/developer-platform/generated/ott

> lucybot@4.0.4 build:client /usr/lib/node_modules/lucybot
> ng build --aot --extract-css

[BABEL] Note: The code generator has deoptimised the styling of "/usr/lib/node_modules/lucybot/node_modules/@angular/core/esm5/core.js" as it exceeds the max of "500KB".
Date: 2018-10-08T12:21:47.756Z
Hash: beb6ce43daa39e23542f
Time: 39751ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 3.89 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 760 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 1.62 MB [initial] [rendered]
chunk {scripts} scripts.bundle.js, scripts.bundle.js.map (scripts) 502 kB [initial] [rendered]
chunk {styles} styles.bundle.css, styles.bundle.css.map (styles) 159 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 3.22 MB [initial] [rendered]

ERROR in ./src/app/styles/bootstrap.scss
Module build failed: Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (64)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
    at module.exports (/usr/lib/node_modules/lucybot/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/usr/lib/node_modules/lucybot/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/lib/node_modules/lucybot/node_modules/sass-loader/index.js:4:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
ERROR in ./src/app/styles/styles.scss
Module build failed: Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (64)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
    at module.exports (/usr/lib/node_modules/lucybot/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/usr/lib/node_modules/lucybot/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/lib/node_modules/lucybot/node_modules/sass-loader/index.js:4:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
ERROR in ./src/app/styles/components.scss
Module build failed: Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (64)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
    at module.exports (/usr/lib/node_modules/lucybot/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/usr/lib/node_modules/lucybot/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/lib/node_modules/lucybot/node_modules/sass-loader/index.js:4:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
ERROR in ./src/app/styles/bootstrap.scss
Module build failed: ModuleBuildError: Module build failed: Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (64)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
    at module.exports (/usr/lib/node_modules/lucybot/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/usr/lib/node_modules/lucybot/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/lib/node_modules/lucybot/node_modules/sass-loader/index.js:4:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at runLoaders (/usr/lib/node_modules/lucybot/node_modules/webpack/lib/NormalModule.js:195:19)
    at /usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:170:18
    at loadLoader (/usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/loadLoader.js:27:11)
    at iteratePitchingLoaders (/usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/usr/lib/node_modules/lucybot/node_modules/webpack/lib/NormalModule.js:182:3)
    at NormalModule.build (/usr/lib/node_modules/lucybot/node_modules/webpack/lib/NormalModule.js:275:15)
ERROR in ./src/app/styles/styles.scss
Module build failed: ModuleBuildError: Module build failed: Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (64)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
    at module.exports (/usr/lib/node_modules/lucybot/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/usr/lib/node_modules/lucybot/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/lib/node_modules/lucybot/node_modules/sass-loader/index.js:4:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at runLoaders (/usr/lib/node_modules/lucybot/node_modules/webpack/lib/NormalModule.js:195:19)
    at /usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:170:18
    at loadLoader (/usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/loadLoader.js:27:11)
    at iteratePitchingLoaders (/usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/usr/lib/node_modules/lucybot/node_modules/webpack/lib/NormalModule.js:182:3)
    at NormalModule.build (/usr/lib/node_modules/lucybot/node_modules/webpack/lib/NormalModule.js:275:15)
ERROR in ./src/app/styles/components.scss
Module build failed: ModuleBuildError: Module build failed: Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (64)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
    at module.exports (/usr/lib/node_modules/lucybot/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/usr/lib/node_modules/lucybot/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/lib/node_modules/lucybot/node_modules/sass-loader/index.js:4:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at runLoaders (/usr/lib/node_modules/lucybot/node_modules/webpack/lib/NormalModule.js:195:19)
    at /usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:170:18
    at loadLoader (/usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/loadLoader.js:27:11)
    at iteratePitchingLoaders (/usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/usr/lib/node_modules/lucybot/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/usr/lib/node_modules/lucybot/node_modules/webpack/lib/NormalModule.js:182:3)
    at NormalModule.build (/usr/lib/node_modules/lucybot/node_modules/webpack/lib/NormalModule.js:275:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lucybot@4.0.4 build:client: `ng build --aot --extract-css`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lucybot@4.0.4 build:client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by tan-tan-kanarek** [comment]
Note that it used to work on this server until September 12th.

**Comment by jessp01** [comment]
Hi @tan-tan-kanarek,

Can you please try to upgrade to the latest lucybot NPM?
```sh
# npm install -g https://$GITHUB_ACCESS_TOKEN@github.com/LucyBot-Inc/documentation-generator#v4.2.0"
```

Note that you can always check the latest version used by the CD process here:
https://github.com/kaltura/developer-platform/blob/master/.travis.yml#L5

Thanks,

**Comment by jessp01** [comment]
@tan-tan-kanarek - can this be closed?

**Comment by jessp01** [comment]
@tan-tan-kanarek - I'm closing this one as I believe it's no longer relevant. Please reopen if not so.

**Comment by tan-tan-kanarek** [comment]
Thanks
